### PR TITLE
Fix contrast for pastebin icon

### PR DESCRIPTION
**Pull request by drakeerv**
I realized that the contrast between the pastebin black icon and the dark mode background was low so I colored in the icon with white and grey to improve contrast.

### CODE REVIEW

**Comment by ManeraKai** [comment]
Thanks :)

**Comment by ManeraKai** [comment]
I merged it too fast. You can have one svg for the light theme, and one svg for the dark theme.

**Comment by ManeraKai** [comment]
I reverted the PR.

**Comment by drakeerv** [comment]
The one icon should be good for both light and dark.

**Comment by drakeerv** [comment]
Screenshot 2024-08-14 at 17-18-16 Merge pull request #970 from libredirect_revert-968-master · dragynfruit_libredirect@25be22d

New on left, Old on right

**Comment by ManeraKai** [comment]
Yes please.

**Pull request merged**
