### PR TITLE
switchInstance returns next instance instead of random

### PR DESCRIPTION
**Pull request by orfins**
I usually have 1-2 instances, and attempting to switch between them and get the same instance 5+ times in a row is annoying, especially on mobile :)

### CODE REVIEW

**Comment by ManeraKai** [comment]
This should not happen, can you record a video of it?

**Comment by orfins** [comment]
If possible please elaborate what you mean by "should not happen".

Anyway:

https://github.com/libredirect/browser_extension/assets/24619811/baa38cb7-f7ab-4a77-bf98-4398e7ba3612

At 00:00 you can see that I'm running from current `master` branch
At 00:23 I enabled libredirect for YouTube and choose 2 instances.
At 00:30 I clicked `Switch Instance` button multiple times and got the same instance multiple times in a row. Same goes for the button at the top near the YouTube toggle.
At 01:03 I start closing and reopening the extension window between attempts, and consistently getting the other instance every time.
At 01:18 I add another instance (total of 3) and you can see that I jump back and forth between `puffyan` and `fdn` before I eventually get `vern`. Of course I still have to close and reopen the window between attempts.

My observations from the video:
1. When you have 2 instances, you have to close and reopen the extension window in order to spam switch between them (there are good reasons to spam switch between 2 instances such as both of them being rate limited during peak hours, making you have to spam to eventually receive a response).
2. When you have more than 2 instances, spam switching between them is not equal and causes starvation.

**Comment by ManeraKai** [comment]
It's because you didn't close the popup.

**Comment by orfins** [comment]
Yeah I've mentioned that, but the other points are still relevant don't you think?

**Comment by ManeraKai** [comment]
So it's between using random, and using sorted listing.

**Comment by ManeraKai** [comment]
Thanks! :)

**Pull request merged**
