### PR TITLE
WWW regex improve

### PR DESCRIPTION
**Pull request by NoPlagiarism**
- removed useless `|` in groups (`(if1|if2|)` -> `(if1|if2)`)
- make `www` optional everywhere I could (fixed twitter, cuz it's not redirects to www)
- Make some groups non-capturing

### CODE REVIEW

**Comment by ManeraKai** [comment]
No need to make some groups "not capturing", just to be simpler.

**Comment by NoPlagiarism** [comment]
Idk, just noticed that some simple groups aren't captured. So made all of that "100% no need in the future"-like groups non-captured

opera_DYETriecb7

**Comment by ManeraKai** [comment]
I see, could be bc of our past old structure. Our current structure doesn't use this regex for any matching thing.

**Comment by ManeraKai** [comment]
Thanks! :)

**Pull request merged**
