### PR TITLE
Snopes Frontend & Librarian Frontend Are Down

### PR DESCRIPTION
**Pull request by xbdmHQ**
The Librarian pussied out lol: https://bcow.xyz/posts/archiving-librarian/

Suds been down for quite some time, might remove it for the time being and then re-add it if he's going to come back.

Source code: https://git.vern.cc/cobra/Suds
Wayback Machine: https://web.archive.org/web/20230314215806if_/https://git.vern.cc/cobra/suds

### CODE REVIEW

**Comment by ManeraKai** [comment]
Ok remove librarian,  but not Suds since we still don't know what happened to it (like wikiless)

**Comment by xbdmHQ** [comment]
> Ok remove librarian, but not Suds since we still don't know what happened to it (like wikiless).

Oh, wikiless is [here](https://github.com/Metastem/wikiless)

**Comment by ManeraKai** [comment]
No that's a fork, I'm still confused though about it.

**Comment by xbdmHQ** [comment]
> No that's a fork, I'm still confused though about it.

Yeah, same but it seems to be maintain

**Comment by su-klubert** [comment]
> pussied out

nice language towards a dev where your opinion you disagree. i would most likely agree with u on that topic but it was his project. its foss, everyone can continue it and instances still work. so its his take, i dont share it. but its his decision. at least show some respect for the work he has put into providing the front end. 

so why remove it and use the more retarded lbry app instead of the good web app he produced. 

> Suds been down for quite some time, might remove it for the time being and then re-add it if he's going to come back.

looks like ur the pussy, since instances still work and u want to have it removed due to the project no longer being maintained while working fine. force users to use the more retarded lbry app, looks like a bunch of dumb shit mentioned in one spot. I respect u all, but still think ur takes shit.

**Comment by xbdmHQ** [comment]
lbry is closed source and they also privacy as well, they have a discord. they will probably block the frontend anyways

**Comment by su-klubert** [comment]
they did not over the time it was maintained as far as i know. so please argue with reason instead of providing more shit to read.

> lbry is closed source and they also privacy as well, they have a discord

???

**Pull request merged**
