### PR TITLE
Add redirects from Tumblr blogs to Priviblur

### PR DESCRIPTION
**Pull request by syeopite**
Example URLs:

```
https://staff.tumblr.com/ ----> https://pb.bloat.cat/staff/
https://staff.tumblr.com/post/736071326097440768/hello-tumblr-this-is-a-badges-update ----> https://pb.bloat.cat/staff/736071326097440768/hello-tumblr-this-is-a-badges-update

https://www.staff.tumblr.com ----> https://pb.bloat.cat/staff
```

### CODE REVIEW

**Comment by ManeraKai** [comment]
Please tell me if my modified regex is giving problems.

**Comment by syeopite** [comment]
That works but you'll need to add hyphens into the character set there since Tumblr blog names can include hyphens. For example:

```
https://firefox-official.tumblr.com
https://staffs-secret-blog.tumblr.com
```

**Comment by ManeraKai** [comment]
I swear I added hyphens... I think I didn't commit that. I'll add.

**Comment by ManeraKai** [comment]
Added it.

**Pull request merged**
